name: Upload images to S3
on:
  push:
    paths:
      - "**.jpg"
      - "**.png"
      - "**.webp"

jobs:
  images_to_s3:
    runs-on: macOS-latest
    name: Upload images to S3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Upload images
        uses: ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
        with:
          image_path: "./img/staging/"
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Delete uploaded images"
          git push
